import { Container, Theme } from "@radix-ui/themes";
import type { Metadata } from "next";

import "@radix-ui/themes/styles.css";
import "./globals.css";
import NavBar from "./NavBar";

import { Quicksand } from "next/font/google";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${quicksand.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Theme accentColor="orange">
          <NavBar />
          <main className="p-5">
            <Container>{children}</Container>
          </main>
        </Theme>
      </body>
    </html>
  );
}
